[build]
  publish = "."

[forms]
  settings = { spam_protection = true }

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
